name: TEST

on:    
    workflow_dispatch:

jobs:
    build:    
        runs-on: ubuntu-latest
        steps:
          - name: Checkout current repo
            uses: actions/checkout@v2 # checkout the repository content to github runner
            
          - name: setup python
            uses: actions/setup-python@v4
            with:
                python-version: '3.9' # install the python version needed
        
          - name: Upgrade Pip
            run: |
                python -m pip install --upgrade pip
                
          - name: Use readme-lol-stats-action
            uses: rithikasilva/readme-lol-stats-action@master # checkout the repository content to github runner
            with:
                source: ${{ github.event.repository.name }}
                pat: ${{ secrets.MY_PAT }}
                api-key: ${{ secrets.API_KEY }}
                github-token: ${{ secrets.GITHUB_TOKEN }}

                
          - name: commit files
            run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add -A
                git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
            
            
          - name: push changes
            uses: ad-m/github-push-action@v0.6.0
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: main 
